### ISSUE TITLE
Broken link to slides

### ISSUE THREAD

**Issue by Prakash2403** [NCBI-Hackathons/VirusDiscoveryProject#11]
[docs.google.com/presentation/d/1U9_ryV0uzO0VXC77vzhur2lJmBunA4F5aNSmhQXrgJU/edit#slide=id.g4a4e9be9b9_41_11](docs.google.com/presentation/d/1U9_ryV0uzO0VXC77vzhur2lJmBunA4F5aNSmhQXrgJU/edit#slide=id.g4a4e9be9b9_41_11) 

This link is mentioned in the README, under the section `Detection of novel contigs and novel viruses
`. However, it is broken. Can you kindly update it?

**Comment by glickmac** [comment]
Try this, https://docs.google.com/presentation/d/1NGXwqCb5mgfOGq4jqpiK5cjHoW48sMGTLPX0IglHIOE/edit?usp=sharing
